### ISSUE TITLE
Wrap error with webpack

### ISSUE THREAD

**Issue by SilverLeaves** [tambien/Piano#12]
(node:1044) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ webpack -p
(node:9492) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

 ERROR in ./build/Demo.js from UglifyJs
    Unexpected token: operator (>) [./~/midiconvert/src/Util.js:20,0][./build/Demo.js:28240,15]

**Comment by SilverLeaves** [comment]
I think you should rewrite this repository. there are many thing no work correcttly!

**Comment by SilverLeaves** [comment]
This issue may apears sometimes. but it can make firefox page crash
by the way, beacuse I can't wrap so I change the music src folder to './Salamander/' in './build/demo.js'
firefox log:
处理 decodeAudioData 时发生未知错误。
169.254.18.163
09:13:58.146
Unhandled promise rejection Tone.Buffer: could not decode audio data: ./Salamander/Ds2v12.mp3

**Comment by tambien** [comment]
going to close. stale issue, hopefully was addressed in latest refactor and typescript update
