### ISSUE TITLE
Doesn't work without webmidi

### ISSUE THREAD

**Issue by fletcherist** [tambien/Piano#19]
Hello! Thanks for the beautiful library!
You have mentioned in [README](https://github.com/tambien/Piano#install)
```
npm install --save tone
# optional
npm install --save webmidi
```
however If install only this package, and not installing webmidi, it fails with the following error message:
```
./node_modules/@tonejs/piano/build/midi/MidiInput.js
Module not found: Can't resolve 'webmidi' in '/Users/fletcherist/jamsandbox/node_modules/@tonejs/piano/build/midi'
```

is it yet optional or required? thanks in advance

**Comment by tambien** [comment]
It's required now. I'll update the README
