### ISSUE TITLE
Did you think of opening this design to other instruments ?

### ISSUE THREAD

**Issue by cmigliorini** [tambien/Piano#21]
Hi,

I'm using Piano (love it, it's great!) in an app that creates musical dictations and was thinking of offering other instruments as well.

By the look of it, I was thinking there is a potential for using the program structure to create, say, a guitar, perhaps a flute, using other samples...

Did you already look into this? I'd be happy to work on it.

Christophe.

**Comment by tambien** [comment]
Hi Chrisophe, the library is really built around the Salamander dataset. i think if there was a similarly high-quality multisampled dataset for guitar or flute, that'd be really cool i haven't found one myself, but i also haven't looked very hard.

Let me know if you know of any good sample-packs with a useable license

**Comment by cmigliorini** [comment]
I was thinking of samples from UIowa, e.g. http://theremin.music.uiowa.edu/MISguitar.html
