### ISSUE TITLE
deprecated GainNode.gain.value setter

### ISSUE THREAD

**Issue by resource0x** [tambien/Piano#7]
First, thanks for excellent piano, I'm going to use it in my project (https://chat.concert0x.com).
Just one hiccup:
Chrome complains:
Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

Could you fix it?
Thanks,
Alex

**Comment by tambien** [comment]
cool project! there's nothing that needs fixing with this warning. Chrome has finally updated to the _correct_ behavior of `gain.value`, and they put this error message if you still wanted to use the older non-spec compliant behavior, you should use setTargetAtTime instead. Shouldn't affect anything Tone.js or Piano.js-wise.

**Comment by resource0x** [comment]
If you are curious, I added Salamander, you can select it from output menu and then play tunes from demo menu, e.g 'crazy_rag' or anything. Salamander makes a huge difference :)
One thing I found out was that the default timing of Tone.now() was no good, program printed lots of console.warn messages complaining about the time in the past, and playback was quite rough b/c low-freq noise. I added 0.03 seconds to Tone.now() while calling. I think no one tested it before with live playing, but I use it exactly for live playing, and even when program plays pre-recorded demos, it invokes the synth in realtime, b/c in general, the output is a MIDI device that doesn't support timestamps. So I have timeline scheduler in my program anyway (not relying on downstream drivers). But this is no big deal,
Again, thanks for this little gem, it's certainly the best sw piano synth for the web today.
Alex
