### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [tambien/Piano#9]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

Greetings

**Comment by tambien** [comment]
@nunojesus wow! thanks! post a link or send a PR so i can check it out 

really appreciate it! looking forward to seeing it 😀

**Comment by nunojesus** [comment]
Here is the logo that also works as icon.
The concept its a Piano and sampled.
I hope you like it, if not, just tell me and I will make another one, if you want changes as colors just say it

The name it´s just Piano?

Greetings

![piano](https://user-images.githubusercontent.com/34600369/39456957-2045d376-4ce2-11e8-8730-a1066344e334.png)

**Comment by tambien** [comment]
this is awesome! thank you so much. definitely going to use it

**Comment by nunojesus** [comment]
Im happy you like it, I will make the files and I will send it to you. The name is just Piano?

**Comment by tambien** [comment]
Let’s go with “Piano.js”. feel free to send it in a pull request so that you get credit for it on github as a collaborator.

**Comment by nunojesus** [comment]
I will put that name in the logotype, I will send you also the icons.
I will try to make the pull request today.

**Comment by nunojesus** [comment]
Im going to make the PR now with all the files 

![pslogotype1](https://user-images.githubusercontent.com/34600369/39536551-dad423d0-4e2e-11e8-98a8-deec06a6dfbf.png)


![pslogotypewhite](https://user-images.githubusercontent.com/34600369/39536554-db3ef688-4e2e-11e8-84c3-954318452811.png)


![pslogotypeblack](https://user-images.githubusercontent.com/34600369/39536553-db1f063e-4e2e-11e8-892a-3b10c30cdab7.png)

**Comment by nunojesus** [comment]
I made the pull request, dont forget to merge :)

Greetings and good luck for your project!

**Comment by nunojesus** [comment]
Hi, can you merge the pull request please, to finish this project and add this to my logo portfolio. Thanks

**Comment by tambien** [comment]
sure! closed by #10
